openapi: 3.0.0
info:
  title: H plus API
  version: 1.0.0
tags:
  - name: product
    description: This part create block of paths.
  - name: article
    description: Articles for H Plus Sport App
paths:
  /product/{productId}:
    get:
      tags:
        - product
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: integer
            example: 1234
        - in: header
          name: optional parameter
          required: false
          schema:
            type: integer
            example: 45
      responses:
        200:
          description: Returns product with parameter id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
            application/xml:
              schema:
                $ref: "#/components/schemas/Product"
        400:
          $ref: 'https://api.swaggerhub.com/domains/DemoOrganization_1/common/1.0.0#/components/responses/GeneralError'
        500:
          $ref: "#/components/responses/500APIError"
  /product:
    post:
      description: Add new product.
      tags:
        - product
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        201:
          description: Product has been created.
        500:
          $ref: "#/components/responses/500APIError"
                    
    get:
      tags:
        - product
      parameters:
        - $ref: "#/components/parameters/PageNumber"
        - $ref: "#/components/parameters/PageSize"
      responses:
        200:
          description: Returns list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        500:
          $ref: "#/components/responses/500APIError"
          
  /article:
    get:
      tags: 
        - article
      responses:
        200:
          description: Returns list of article
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Article"
components:
  parameters:
    PageNumber:
      in: query
      name: pageNumber
      description: Page number to return
      required: false
      schema:
        type: integer
        example: 1
    PageSize:
      in: query
      name: pageSize
      description: Number of items in the page
      required: false
      schema:
        type: integer
        example: 20    
        maximum: 100
  schemas:
    Product:
      type: object
      required:
        - name
        - description
      properties:
        id:
          type: integer
          example: 400
        name:
          type: string
          example: lemon water
        description:
          type: string
          example: details of the product
        image_title:
          type: string
          example: image title
        image:
          type: string
          example: https:www.hyper-link-to-image.com
        image-alt:
          type: string
          example: image text
    Article:
      type: object
      properties:
        id:
          type: integer
          example: 12
        header: 
          type: string
          example: This is a article header
        content:
          type: string
          example: This is content of the article (long text article)
        createdDate:
          type: string
          format: date
          example: 12.12.2022
        tags:
          type: array
          items:
            type: string
  responses:
    500APIError:
      description: This is an unexpected api error.
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: string
                example: 500
              massage:
                type: string
                example: This is generic api error for 500